version: '3'
services:
  micromq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=1
      - BROKER_LISTEN_PORT=7270
      - BROKER_MAX_OPEN_SIZE=20
      - BROKER_TOKEN=${BROKER_TOKEN}
      - BROKER_HEARTBEAT_TIMEOUT=100
      - BROKER_MESSAGE_ENCRYPT=true
      - BROKER_MESSAGE_ENCRYPT_OPTION=TOKEN
      - EDGE_LISTEN_PORT=7280

    ports:
      - "7270:7270"
      - "7280:7280"

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: "20m" # 限制每个日志文件大小
        max-file: "15" # 保留最近日志文件天数

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'

    restart: always
