version: '3'
services:
  micromq-broker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: micromq-broker
    environment:
      - DEBUG=${DEBUG}
      - BROKER_CORE_LISTEN_PORT=7270
      - BROKER_MAX_OPEN_SIZE=${BROKER_MAX_OPEN_SIZE}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - BROKER_HEARTBEAT_TIMEOUT=100
      - BROKER_MESSAGE_ENCRYPT=${BROKER_MESSAGE_ENCRYPT}
      - BROKER_MESSAGE_ENCRYPT_OPTION=${BROKER_MESSAGE_ENCRYPT_OPTION}
      - BROKER_EDGE_LISTEN_PORT=7271

    ports:
      - "7270:7270"
      - "7271:7271"

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: "20m" # 限制每个日志文件大小
        max-file: "15" # 保留最近日志文件天数

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'

    restart: always
