version: '3'
services:
  micromq-web:
    container_name: micromq-web
    build:
      context: ../website
      dockerfile: Dockerfile

    ports:
      - "7272:80"
    volumes:
      - "./nginx/nginx-web.conf:/etc/nginx/conf.d/nginx.conf"

    logging:
      driver: json-file
      options:
        max-size: "10m"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'

    restart: always